### ISSUE TITLE
diagram support such as plantuml

### ISSUE THREAD

**Issue by capsulecorplab** [pillar-markup/Microdown#100]
I currently use the [asciidoctor-diagram](https://asciidoctor.org/docs/asciidoctor-diagram/) plugin for [asciidoctor](https://asciidoctor.org) which allows embedding plantuml syntax or files directly in asciidoc. It looks like there's [PlantUMLPharoGizmo](https://github.com/fuhrmanator/PlantUMLPharoGizmo), which allows previewing plantuml within Pharo - could this perhaps be extended to also work in microdown?

**Comment by capsulecorplab** [comment]
Opened an [issue](https://github.com/fuhrmanator/PlantUMLPharoGizmo/issues/11) for reference.

**Comment by Ducasse** [comment]
Thanks for the suggestion. Now time is super scarce and the roadmap is 
- new release
- clean baseline of Pillar
- work on PillarMicro (pillar using microdown)
- make sure that we can load help in microdown

**Comment by kasperosterbye** [comment]
I do believe one could allow the syntax:

```language=plantuml
plantuml
```
to produce a plantuml diagram to be inserted into the location of the code-block. This would be somewhat similar to the way Latex is rendered. I think most of the infrastructure to do so is in my repositories.

**Comment by kasperosterbye** [comment]
I would like to do this one for Pharo 11. It is a cool thing.
I imagine it to be a separate package in the Microdown project, and will utilise the same infrastructure as Latex.

It is a question if one should use
```text
   ```language=plantuml
or
   &language=plantuml
```

One reason to go for the latex-style would be that:
- \``` is intended to provide formatting (highlighting) to the embedded text
- <! is intended to microdown parse its embedded structure
- & is intended to process its embedded text and produce a different thing (an image)

Or in other words, & is the consistent choice (or I have misunderstood the above list). 

In either case, the actual extension mechanism need to be created.

**Comment by kasperosterbye** [comment]
PR #401 gives us extension in the `&` which is a prerequisite.
I updated my repository https://github.com/kasperosterbye/PlantUmlMicrodownExtension to support plantuml using this extension.

![image](https://user-images.githubusercontent.com/17723745/166894392-4908071f-4892-4335-8c9e-e8bc6b6dd52f.png)

**Comment by kasperosterbye** [comment]
I like it to be something separate, Microdown project is big enough as it is, and https://github.com/kasperosterbye/PlantUmlMicrodownExtension can also serve as an example of how to make such extensions.

**Comment by Ducasse** [comment]
I like the idea of the extension.

**Comment by kasperosterbye** [comment]
But we can consider moving extension to pillar-project (instead of it living in my place), so it becomes a sister to Microdown.

**Comment by kasperosterbye** [comment]
It lives just fine in my rep, and I close this issue
