### ISSUE TITLE
PRRichTextComposer>>visitExternalLink: aLink @ Pharo8 / Windows

### ISSUE THREAD

**Issue by sbragagnolo** [pillar-markup/Microdown#105]
Pharo 8 64 bits Windows 10. 

PRRichTextComposer>>visitExternalLink: aLink
Uses a block for opening the link that do as following: 
[WebBrowser openOn: target].

Target seems to be interpreted as a ZnUrl, what is fine. The problem is that WebBrowser expects a StringURL, and it ends up in a FFI marshalling exception. 

To add asString to the target seems to do the trick. But It is this the kind of solution we should think? 
Personally I would rather use always Url objects, instead of string and pass the problem to WebBrowser. 

Do you see any reason for doing it in microdown instead than in WebBrowser?

**Comment by kasperosterbye** [comment]
The PRRichTextComposer is superseded by Microdown in Pharo9 and Pharo10, and links are done different today. I close it now, you are welcome to reopen it.
