### ISSUE TITLE
#PRRichTextComposer>>visitFigure: Does not contemplate image size

### ISSUE THREAD

**Issue by sbragagnolo** [pillar-markup/Microdown#106]
The parser is prepared for accepting scaling of images like
![ROS](https://www.ros.org/wp-content/uploads/2013/10/rosorg-logo1.png|size=200&caption=ROS)
During the text composition this size is not used. 
I have a small fix that use the form scaling with this value. 

Is this a good contribution? Or it would be better to accept size=200 and size=200@100 ?. (my fix now is only doing x@x instead of x@y).

**Comment by Ducasse** [comment]
Yes this is a nice contribution please send it :).

**Comment by kasperosterbye** [comment]
It is stille a good idea...

**Comment by kasperosterbye** [comment]
This is currently done using `![](image_url "width=200&height=200")`
