### ISSUE TITLE
This comment breaks microdown.

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#107]
I'm a simple lexer. I'm used bt the DLitlleLParser.

I recogniseI 
	- names: list of characters letter and number and '
	- separators: one character separator. 
	- escape char \

Whitespaces and separators can be customised using setters.
Subclasses may change the definition of names by redefining isCurrentALetter.

**Comment by Ducasse** [comment]
if you paste the following comment in a class comment in latest Pharo.... boum you get a DNU and it should not. 
No idea why in fact.

**Comment by Ducasse** [comment]
In Pharo 9.0.0
Build information: Pharo-9.0.0+build.1141.sha.52858aa78ba53f37200510df2cfc3e386f80d341

**Comment by Ducasse** [comment]
The bug is that if \ is the last element there is no other element to escape.

**Comment by kasperosterbye** [comment]
This is related to the overall issue of ` \` handling.
