### ISSUE TITLE
CHeck + because it is declared as unordered markup or ordered markup

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#109]
but it is not used. 
Check the parser class side methods.

**Comment by kasperosterbye** [comment]
As far as I can see, `MicUnorderedListBlock>>canConsumeLine:`
```smalltalk
canConsumeLine: line
	"to consume this line there must be a UnorderdListItem start at the right indentation"

	line ifEmpty: [ ^ true ].
	^ (super canConsumeLine: line) and: [line trim matchesRegex: '(^\* |^- | ^\+).*']
```
accepts `+` as an item beginning. And `MicOrderedListBlock>>canConsumeLine:` does not. 

Why did you think there is a problem?

**Comment by Ducasse** [comment]
I do not remember may be I did not want to support +

**Comment by kasperosterbye** [comment]
OK - I leave it open and ask you again next time I examine all issues :-)

**Comment by kasperosterbye** [comment]
The legal options are still +,- and *. I think we leave it like this and close it
