### ISSUE TITLE
fixing test MicCodeBlockTest >> testSingleCodeBlockTwoLinesAsPillar

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#117]
MicCodeBlockTest
352
 ✗ #testSingleCodeBlockTwoLinesAsPillar (77ms)
353
TestFailure: Got '' instead of 'ArgumentGoesHere'.
354
MicCodeBlockTest(TestAsserter)>>assert:description:resumable:
355
MicCodeBlockTest(TestAsserter)>>assert:description:
356
MicCodeBlockTest(TestAsserter)>>assert:equals:
357
MicCodeBlockTest>>testSingleCodeBlockTwoLinesAsPillar ...assert: code language originalName equals: 'ArgumentGoesHere'
358
MicCodeBlockTest(TestCase)>>performTest
359

**Comment by Ducasse** [comment]
see #111

**Comment by kasperosterbye** [comment]
The test is now `MicCodeBlockTest>>testSingleCodeBlockTwoLines" and is all green. I believe it might be an error from the old argument splitter. I close it now.
