### ISSUE TITLE
annotations are wrongly extracted

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#126]
```
blbabbab <?footnote | value=A foonote is annotation.?>
```
the second element should have footnote as name and parameters Key =value and value for this key = A foonote.....

**Comment by kasperosterbye** [comment]
I believe this is fixed by PR #222. But I will make a test to be sure.

**Comment by Ducasse** [comment]
Thanks I will have a look. 
I will try to contact you in the afternoon after 16:00 (teaching until 15:30) and meeting at 16:30

**Comment by kasperosterbye** [comment]
Confirmed that this issue was related to #218, and solved by #222.

I'll be on discord this afternoon at the above time. 
I am in particular interested plans for the help system and overall directions.
