### ISSUE TITLE
testSplitBlockAnnotation is wrong

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#127]
testSplitBlockAnnotation
	| res |
	res := self splitter start: 'abc<?an annotation?>def'.
	self
		assert: (res collect: [ :x | x printString ])
		equals: {'abc' . '[an annotation](annotation)' . 'def'}.
	self assert: (res second isKindOf: MicAnnotationInlineBlock)

**Comment by Ducasse** [comment]
We should revisit inline block printOn: 
right now we get 

[[italicitalic](italic)](bold) for **_italicitalic_** and the problem is that displaying **_italicitalic_** is not optimal because we cannot distinguish between text and structure.
but [[italicitalic](italic)](bold) is confusing because we do not have a link.

**Comment by kasperosterbye** [comment]
This is two issue I believe - the problem with `MicInlineParserTest>>testSplitBlockAnnotation` was an issue with the old argument splitter. The test is now green. 
I move the inline block printOn: problem to a new issue (#279) and close this one.
