### ISSUE TITLE
MicCOdeBlock>>printOn: is ignoring totally the parameters.... 

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#129]
and this is bad.

```
printOn: aStream

	aStream nextPutAll: 'Code: '.
	aStream nextPutAll: (self code asString contractTo: 100)
```

is wrong

**Comment by kasperosterbye** [comment]
The `printOn:` message is no longer implemented in `MicCodeBlock` - and hence no longer wrong :-)

**Comment by Ducasse** [comment]
I do not think that the printString is good. This is unrelated to printOn: or not in codeBlock

**Comment by kasperosterbye** [comment]
Obsoleted
