### ISSUE TITLE
Comments in markdown

### ISSUE THREAD

**Issue by kasperosterbye** [pillar-markup/Microdown#154]
Github markdown supports html style comments `<!-- I am a comment -->`.

When I originally wrote the parser, I had in my intentions to be able to be as compliant with github markdown as possible. The idea was to keep a door open in which micromarkdown could be used in readme files, and on the other hand, github readme files should be able to be shown in-image.

At the time I wrote it, github did not support comments (or I could not find them). It should not be too difficult to simply add a step in the parser that removes comments.

**Comment by Ducasse** [comment]
Thanks we should check that. 
Right now we have % line for line based comment. 
Now I hate such html style comments they should have make them even more verbose.

**Comment by kasperosterbye** [comment]
HTML and XML are rather unique formats as they are neither good for humans nor computers.

**Comment by kasperosterbye** [comment]
I have discovered that github markdown has a few more variations on comments. 
A line that starts with: '[my comment]:#' is not rendered if the previous line is empty

[this is not rendered]:#

For extension points inline one can also use "false links": `[](latex://somethingwithoutspace)`, or `[](#latex:withoutspace)`

**Comment by Ducasse** [comment]
thanks for the information.

**Comment by kasperosterbye** [comment]
Here is the latest tidbit, which actually seem to be useful in practice. 

Github will ignore `<?blabla|foo=bar&caption=This is my caption?>`. It could be nice to use this syntax for annotations rather than `?{` and `}?`

**Comment by kasperosterbye** [comment]
This in generally a discussion which is leading nowhere. I will close it for now.
