### ISSUE TITLE
Metacello Loading Error

### ISSUE THREAD

**Issue by rakki-18** [pillar-markup/MicroDown#162]
I tried to load the MicroDown repository in Pharo 9.0 version using
```Smalltalk
Metacello new
  baseline: 'Microdown';
  repository: 'github://pillar-markup/Microdown:dev/src';
  load.
```

But I am getting a `SubscriptOutOfBounds:2` error.
Am I doing something wrong while loading?

**Comment by Ducasse** [comment]
Thanks for reporting I will try it.

**Comment by Ducasse** [comment]
Indeed there is bug in the baselineline...
Let us investigate it.

**Comment by Ducasse** [comment]
The problem is that the baseline of microdown is done to be loaded inside the shipped version of Pharo. 
If you want to try you can take the development version 

```
Metacello new
  baseline: 'Microdown';
  repository: 'github://pillar-markup/MicrodownDev:dev/src';
  load.
```

We will have to fix the baselineOfMicrodown and when loading forcing the reload of the baseline to take the one in the repository of microdown and not Pharo.

**Comment by Ducasse** [comment]
The development version is nicer. It contains a visitor and an improved structure for text.
We should release a version 2.0 of Microdown by mid July or a bit before.

**Comment by Ducasse** [comment]
We changed the description and provide two versions: 
- the v1.0.5 limited based on pillar and stable
- the dev version with visitor and enhanced model [ to be released soon ]

**Comment by rakki-18** [comment]
> We changed the description and provide two versions:
> 
> * the v1.0.5 limited based on pillar and stable
> * the dev version with visitor and enhanced model [ to be released soon ]

v1.0.5 seems to be working perfectly. Thank you!
I think there is a typo in the description, a colon is missing in the repository name.

**Comment by rakki-18** [comment]
> The development version is nicer. It contains a visitor and an improved structure for text.
> We should release a version 2.0 of Microdown by mid July or a bit before.



> The problem is that the baseline of microdown is done to be loaded inside the shipped version of Pharo.
> If you want to try you can take the development version
> 
> ```
> Metacello new
>   baseline: 'Microdown';
>   repository: 'github://pillar-markup/MicrodownDev:dev/src';
>   load.
> ```
> 
> We will have to fix the baselineOfMicrodown and when loading forcing the reload of the baseline to take the one in the repository of microdown and not Pharo.

I got a loading error ( `subscriptOutOfBound`) when I tried loading with the dev version.

**Comment by Ducasse** [comment]
Thanks I will check. This is strange that the dev version is not working because we load everyday. I will check on a fresh image.

**Comment by Ducasse** [comment]
I copied pasted 

```
Metacello new
  baseline: 'Microdown';
  repository: 'github://pillar-markup/Microdown:v1.0.5/src';
  load.
```
in Pharo 90 and it loads without problem.

**Comment by Ducasse** [comment]
Ok this is 

```
Metacello new
	baseline: 'MicrodownDev';
	repository: 'github://pillar-markup/Microdown:dev/src';
	onConflict: [ :ex | ex useIncoming ];
	onUpgrade: [ :ex | ex useIncoming ];
	load.
```

**Comment by rakki-18** [comment]
> Ok this is
> 
> ```
> Metacello new
> 	baseline: 'MicrodownDev';
> 	repository: 'github://pillar-markup/Microdown:dev/src';
> 	onConflict: [ :ex | ex useIncoming ];
> 	onUpgrade: [ :ex | ex useIncoming ];
> 	load.
> ```

This works. Thank you!
