### ISSUE TITLE
Not happy with transformation

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#201]
As a general remark I do not like that the input extension can produce documents that are not correct from a parser 
point of view. For example we have a paragraph containing a header and this is what the transformation of the includer is doing.

This is because the ?{inputFile|path=bla.pillar}? is inside a block.

**Comment by Ducasse** [comment]
We see two paths for resolving this issue:
- one adding an expansion that expands elements at the top level (extended elements should be children of root (independently of their nesting levels.
- using an environment

For the second case, using an environment, it implies modifying the parser because right now
```
<?inputFile|path=foo.pillar?>
```

is not parsed correctly and we are forced to write

```
<?inputFile|path=foo.pillar
?>
```

**Comment by kasperosterbye** [comment]
I believe it makes sense to restrict input to block level rather than inline.

Which block syntax to hijack is not quite obvious to me. I believe it would be best with a single line block.

As it is now, there is no single line block that can be extended.

**Comment by kasperosterbye** [comment]
Fixed
