### ISSUE TITLE
Microdown Parser should not depend on resolver.

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#204]
Resolver should be called on a unresolved tree.
Probably we should have 
Microdown
    calling the resolver
    and other like the includer.

**Comment by Ducasse** [comment]
This is my current task.

**Comment by kasperosterbye** [comment]
It is marked done in kanban on Sep 30. In addition, PR #289 do not have this issue.

**Comment by Ducasse** [comment]
thanks
