### ISSUE TITLE
Rename MicroDownParser as MicrodownParser and same for others

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#207]
This is currently impossible to save the package once we rename the class.

I will need help from some git expert. Because on mac there is no difference between Microdown and MicroDown so git does not see the difference.

I should probably refactor the code. 
Then force git from the command line to push the changes.

S

**Comment by capsulecorplab** [comment]
Could you describe the git issue in more detail? I don't understand why git wouldn't recognize a change in case

**Comment by Ducasse** [comment]
Because on mac MicroDown and microdown and MicroDOWN are the same from a file system point of view. So once I'm finished with the current issue I will do the renaming from a unix machine and it will work.
