### ISSUE TITLE
printOn: can be improved

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#211]
```
printOn: aStream
	(self kind == #basic) 
		ifTrue: [ aStream nextPutAll: self substring ] 
		ifFalse: [ 
			| contents |
			contents := children 
				ifEmpty: [ self substring ] 
				ifNotEmpty: [ self childrenPrintOn ].
			aStream nextPut: $[;
				nextPutAll: contents;
				nextPut: $];
				nextPut: $(.
			url printOn: aStream.
			aStream nextPut: $) 
		]
```
there is no need for the check.

**Comment by kasperosterbye** [comment]
I assume this is the `MicInlineBlockWithUrl>>printOn:` method.
In that case, I assume you mean it is the `self kind == #basic` test which can be skipped.

**Comment by Ducasse** [comment]
In fact the kind is a design left over from laurine. We should remove kind since we have a hierarchy of nice little objects and little classes.

**Comment by kasperosterbye** [comment]
After the above PR it seems to me that the only use of `kind` is in the tests. There however, it is used extensively and would take some effort to redo. If that should be done, I believe it should be a separate issue.
