### ISSUE TITLE
MicArgumentsSplitter has no tests, and is non-trivial

### ISSUE THREAD

**Issue by kasperosterbye** [pillar-markup/Microdown#218]
It also seems a bit over engineered.

**Comment by kasperosterbye** [comment]
Actually, it is a miracle this thing even works in practice.

As far as I can find out, the syntax this should be able to recognise is this:

- ` ` no name and no arguments
- `name` a single name, no arguments
- `key=arg[&key=arg]*`, no name, but arguments
- `name|key=arg[&key=arg]*` a single name, and arguments

The class has two methods to extract `name`, the method `firstTag` and the method `name`. Both seems to be wrong.

The `name` method assumes there will be a `|` to delimit name from arguments. If no `|` is given, `name`  for `foo=bar&aaa=90` is the entire string `foo=bar&aaa...`.

Similarly the firstTag is wrong as it fails on `foo|bar=99`, returning `foo|bar` rather than `foo` (or `bar`)

Finally, if arguments are prefixed with a name, arguments are not passed correctly.

**Comment by kasperosterbye** [comment]
@Ducasse Is the above understanding of the syntax correct. In that case I will just make a new implementation of MicArgumentsSplitter.

**Comment by Ducasse** [comment]
I copied the code from Zinc because Zinc is nice but I did not want to depend on ZnUtils for two methods.
Now what is important to see is that we want to have the same syntax for url `http://foo.org?b=12&c=10`
and for 
```
   ```language=12&width=33
```

**Comment by Ducasse** [comment]
Now annotation eg ${inputFile| I used | but may be this is better to use ?
What you should also get is that the firstTag is important because without the first tag we cannot determine the kind of annotation it is. So while the firstTag is tag the first one should be identified and not just stored in a simple dictionary. 

Now about the implementation I think that your statement are a bit too strong because so far the argument splitter have been working and figures, inputfile, annotation, code block and more have been all tested. 
So this is not like breaking the argument splitter would not be unnoticed.

**Comment by Ducasse** [comment]
Now feel free to improve this part in particular the cases you identified where the user fills up wrong information and maybe we should deprecate | and use ? I do not remember why I did not.

**Comment by kasperosterbye** [comment]
Just to be clear. A rightly formatted input is split correctly!

I was trying to write tests to examine the error-cases, but if the splitter splits as is do now,  errors in input just pop up elsewhere, where they might or might not be easier to understand.

I believe I will make the tests that demonstrates that the splitter splits correct input correctly, and do not worry about the other cases I mentioned. 

Also, let the change from `|` to `?` be raised in an issue by some who find it confusing. I can surely live with the `|`.

**Comment by kasperosterbye** [comment]
I am afraid I have to adjust my statement above about the splitter doing correctly on correct input.

It only does so if one call the accessors in the right order. For example this test:

```smalltalk
testNameAndArguments
	| subject |
        subject := self subjectUnderTestWith: 'aName|foo=bar'.
	self assert: subject name equals: 'aName'.
	self assert: (subject arguments) size equals: 1.
	self assert: (subject arguments includesKey: #foo)
```

passes, but if one do not ask the splitter for the name before asking for the arguments, it fails because the arguments are then passed first, which make the argument dictionary be: `{#aName|foo -> 'bar'} and name be empty.

I have made a new splitter, which is more robust, I will test it a bit more, and then include it in the PR

**Comment by Ducasse** [comment]
Super!
I like the idea that we redo a pass on things. 
Sometimes I'm not happy but I was in the mood to make it work first.
