### ISSUE TITLE
Latex exporter - code listings

### ISSUE THREAD

**Issue by kasperosterbye** [pillar-markup/Microdown#242]
The current export for code listings is broken, as is the test.

I think the right thing to do is to generate latex for the `listings` latex package. That means that in a real project, one need to add `\usepackage{listings}`. The problem with the listings package is that it requires an external program in addition to latex. The advantage is that is creates nice listings.

I vote for listings.

Alternatively, one could use `verbatim`.

**Comment by Ducasse** [comment]
I have to check because for beamer I learned that we should not use listings.
I would just follow what is done in Pillar. 
I wanted to restart to work on the LaTeXExporter.

**Comment by kasperosterbye** [comment]
OK, I will leave the exporter to you, and split the two builders in the documentation tools.

**Comment by kasperosterbye** [comment]
I tried to use Remark (https://remarkjs.com/#1) to make slides directly in markdown. It works reasonably well, and the supported dialect is rather close to microdown. In particular it is nice with the markdown syntax highlightning.

**Comment by Ducasse** [comment]
Thanks I like the idea of have --- for slides. I was planning to use the extension mechanisms of MD. 
And we need double columns for slides.
But I will check.

**Comment by kasperosterbye** [comment]
Fixed
