### ISSUE TITLE
Add tests for MicHeaderBlock >> header: and headerElements:

### ISSUE THREAD

**Issue by lgrangaud** [pillar-markup/Microdown#248]
header is expecting a text and populates the children of the header
and we should verify that.

headerElements: does it without parsing. ze should verify it too.

**Comment by kasperosterbye** [comment]
Yes, a test that verify that the inline text of the header is actually parsed and stored as children is a good idea. The actual parsing is done in the hook method `closeMe`, but `header` and `headerElements` are good targets for tests.

**Comment by kasperosterbye** [comment]
Somewhere along the line those tests were added. The tests in `MicHeaderBlockTest` include testing of `header` and `headerElements`.
