### ISSUE TITLE
List indentation is inconsistent

### ISSUE THREAD

**Issue by kasperosterbye** [pillar-markup/Microdown#257]
In a bullet list:
```
- item1
- item2
<spacing>-item 3
```
I get different results for *spacing*:
- one space - nothing
- two spaces - 2 indents
- three spaces - 1 indent
- four spaces - one tab indent and one space indent
- one tab is seen as one space and cause no indent

There is also a inconsistent connection for two items following each other:

```
- item1
<spacing1>- item 2
<spacing2>- item 3
```
Strange combinations are (x,y) indicates first number of spaces, second number of spaces
- (3,3) indents both one level
- (2,3) indents both two levels
- (3,2) indents first one level, second none

**Comment by Ducasse** [comment]
I agree that it would be good to fix this.
I just followed what you did originally

**Comment by kasperosterbye** [comment]
Strangely, I must have read the documentation of github lists at the time, because Microdown does the right thing:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/17723745/148635995-1b3f6a81-710c-41ff-a27e-b34d54a567b6.png">

(Taken from https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#lists)

**Comment by Ducasse** [comment]
The best issue... the one already done :)
