### ISSUE TITLE
CodeBlock caption should be managed as children. 

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#282]
Because all the domain elements should be accessible from children. 
Working on it.

**Comment by kasperosterbye** [comment]
Perhaps the argument splitter should be made into a mic node in its own right?

**Comment by Ducasse** [comment]
OK what you are saying is that instead of having a crappy dictionary we could have a MicArgumentNode? Yes this can be interesting because we could have a visit method and reuse it.

**Comment by kasperosterbye** [comment]
I am not quite sure what is the right thing here. The splitter is fine as it is, and for practical reasons there has to be a dictionary somewhere. What I meant was that I saw an alternative to lifting (in the closeMe hook I presume) the caption out of the splitter and into the children of the code-block.

The alternative would be to have a `MicArgumentNode` as you say. The caption is then a child of MicArcumentNode. However, the other arguments have to go somewhere - so the dictionary will most likely be in MicArgumentNode. The splitting into arguments will then be done in the `closeMe` of the MicArgumentNode.

The codeblock will still need some attributes picked out of the splitter (language for example), I do not believe "language" should be stored as a child.

**Comment by kasperosterbye** [comment]
Btw, I like the pragmatic change to children you did with `MicListItemBlock`. The textElements still being accessible in their own right, but also as the beginning of the children. 

I had been thinking of a slightly different way to do it - expressed here in code:
```smalltalk
MicListItemBlock>>closeMe
   | textElements|
   textElements := self inlineParse: text.
   children addFirst: (MicParagraphBlock new text:''; children: textElements).
```
and
```smalltalk
MicListItemBlock>>textElements
   ^ children first
```
and there is no instance variable `textElements` needed

**Comment by Ducasse** [comment]
My point was also that we could have all the management of arguments in a single object instead of having it in codeBlock, math environment and figures.

**Comment by kasperosterbye** [comment]
So that one of the children of say codeBlock is an instance of MicArgumentSplitter (which then need to get MicElement as superclass)?
If this is what you meant, I think that will clean things up a lot.
To get to the arguments in basically any node it will be: `self arguments ...`

**Comment by Ducasse** [comment]
Yes I would call it MicArgument and I'm not sure if it should be a subclass of MicElement but yes this is the idea.

**Comment by kasperosterbye** [comment]
The syntax accepted by MicArgumentSplitter is rougly
`[optionalTag|]?name1=value1?name2=value2`

I suggest that MicArgument be given a new instance variable "defaultArgumentName", so we for example can write ` ```pharo `, and get the value of the argument using arguments at: #language, because for code blocks the defaultArgumentName is `language`.

This is to seamlessly allow both ` ```pharo ` and ` ```language=pharo`

**Comment by kasperosterbye** [comment]
I agree that `MicArgument` is a better name in this usage.

**Comment by kasperosterbye** [comment]
Fixed
