### ISSUE TITLE
Improve MicRichTextComposer API

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#295]
The methods `asRichText:` and `microdownAsRichText:` are misleading and obscure.

It would better to have 
MicRichTextComposer composeMicrodownDocument: aDoc
MicRichTextComposer composeString: aString

or 

MicRichTextComposer richTextFromMicrodown: aDoc
MicRichTextComposer richTextFromString: aString

**Comment by kasperosterbye** [comment]
I tend to disagree on your proposals, but not on the problem :-)

I started in the class Microdown, and it had a method 'parse:' which accepted what one would expect of a parser (a string).
I wanted to be able to write 'Microdown selectorName: argument' to get a Text object from an argument.
There are two kinds of arguments which make sense here - string (with implied parsing), and microdown documents (already parsed).
The selector I picked for Microdown was 'asRichText: ', which I feel is in style with parse: - you kind of know what result you get. 

So actually now I mostly just write 'Microdown asRichText: something' and it does the right thing - I rarely use the long form 'MicRichTextComposer .....'

If I were to pick two names for MicRichTextComposer I would suggest:
MicRichTextComposer textFromDoc: aDoc
MicRichTextComposer textFromString: aString

**Comment by kasperosterbye** [comment]
Nothing was done here. I would suggest two methods to be added (leaving `asRichText:`):
asRichTextFromDoc:
asRichTextFromString:
These two methods should then be available both in Microdown and MicRichTextComposer

Or just leave it as it is now and close the issue.

**Comment by kasperosterbye** [comment]
Fixed
