### ISSUE TITLE
A few release tests fail

### ISSUE THREAD

**Issue by kasperosterbye** [pillar-markup/Microdown#311]
Running the release tests in thest runner - those that appear with filter "release", there are some of the issues reported that are rooted in Microdown. We need to clean up those before release.
<img width="949" alt="image" src="https://user-images.githubusercontent.com/17723745/144803733-1ab8ee87-30b9-4f9b-bea7-0e0aa0f978ba.png">

I believe it is mostly method categories which need to be changed (utils should be utilities) etc. But also a few undeclared variables  (temporary, instance variables and class variables)

**Comment by Ducasse** [comment]
Fixed!
