### ISSUE TITLE
The builder method of MicrodownParser class should be moved to Microdown

### ISSUE THREAD

**Issue by kasperosterbye** [pillar-markup/Microdown#312]
Microdown is the general facade. While one can argue that a builder and a parser belong together, I think they are best each on their own.

**Comment by Ducasse** [comment]
What I was thinking is that we can just provide access to the builder.
We could just write Microdown builder instead of MicrodownParser builder or MicMicrodownTextualBuilder.

**Comment by kasperosterbye** [comment]
Yes, that would be the right way to do it:
Microdown parse:
Microdown builder
Microdown render:
etc

**Comment by kasperosterbye** [comment]
This has been implemented, and is the current practice
