### ISSUE TITLE
Using MicTextPresenter for Text inspection

### ISSUE THREAD

**Issue by kasperosterbye** [pillar-markup/Microdown#326]
It is possible to use `MicTextPresenter` for inspection of Text objects by changing `Text>>inspectionText` from the current implementation to:

```smalltalk
inspectionText
	<inspectorPresentationOrder: 0 title: 'Text'>

	^ MicTextPresenter new text: self
```

I am a bit uncertain where to put this extension method though.

**Comment by Ducasse** [comment]
I will package in the package of the class MicTextPresenter

**Comment by Ducasse** [comment]
The problem is that there is another method so I will tag it differently

```
inspectionText
	<inspectorPresentationOrder: 0 title: 'Text'>

	^ SpMorphPresenter new 
		morph: (RubScrolledTextMorph new 
			setText: self;
			in: [ :this | this textArea readOnly: true ];
			yourself);
		yourself
```

**Comment by kasperosterbye** [comment]
I can confirm that Estebans Spec will work as off tomorrow, so that is good news! 
(I downloaded Spec into a clean image and checked it)

**Comment by Ducasse** [comment]
I was reading the code and I wanted to 
- rename MicTextPresenter SpMorphicTextPresenter because 
- MicScalingTextAnchor to ScalingTextAnchor because it is not linked to Microdown.
- MicScrolledTextMorph into ExtendedScrolledTextMorph 

Is it ok for you if I do some renaming?
The idea is that we can have a package.

**Comment by Ducasse** [comment]
So I was doing it now? Should I continue?

**Comment by kasperosterbye** [comment]
I would like to have the chance to go over it once Esteban has released the new version of spec which actually seems to work. 

My ScalingAnchor thing is new. Lets sit on our hands for a few days.

**Comment by Ducasse** [comment]
Ok I will let you do it. 
Now I really think that we should make clear that some of the classes are not Mic specific.

**Comment by Ducasse** [comment]
I will work go now on the meta issue and my roadmap.

**Comment by kasperosterbye** [comment]
I agree on the some of this is not Mic specific. I got the baton.

**Comment by kasperosterbye** [comment]
The commits Esteban did to Pharo cleared a lot of problems, and standard Pharo now renders Text objects correctly. The only thing missing is the handling of scaleable images and scalable morphs. I still consider this a somewhat experimental feature as there are combinations of width specifications which do not work.

I think it is best to keep it in Microdown rather than general Pharo. When the small quirks has been ironed out we can talk to Esteban on including it in Spec.

**Comment by kasperosterbye** [comment]
Obsolete
