### ISSUE TITLE
What is exactly QuoteBlock?

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#327]
> foo 
> bar
> **foo**

![Capture 2022-01-07 at 11 49 05](https://user-images.githubusercontent.com/432549/148533146-d0b8433d-b4b8-4a04-8a10-76d4d2db294d.png)

**Comment by Ducasse** [comment]
So it means that some tools got it wrong :) but we can follow the GH way. good to know

**Comment by kasperosterbye** [comment]
This is not an annotated block, this is a quote block.

**Comment by Ducasse** [comment]
Yes sorry it was pillar vocabulary
