### ISSUE TITLE
Examples in RichTextComposer are broken

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#332]
There is a problem with SpFont but I do not really get what is the problem.

**Comment by Ducasse** [comment]
In addition 

exampleLatex
	<sampleInstance>

	^ self parseAndCompose:
'V_i = C_0 - C_3
\frac{C_1\cos(\theta_i+C_3)}{C_4+C_1\cos(\theta_i+C_2)}'

is not correct because it is not microdown. 
We should create a math inline or a mathenvironment

**Comment by Ducasse** [comment]
See #### Example 3
Code: `$\\sin(x) = \\sum_{n=0}^{\\infty} \\frac{(-1)^{n}x^{2n+1}}{(2n+1)!}$`
 
in MicMathInlineBlock

**Comment by kasperosterbye** [comment]
I do not know what you problem you had with SpFont.
Are you doing an update of the examples? If not, I will do it.

**Comment by Ducasse** [comment]
For now I cannot I want to finish to make beautiful comment working. 
For the font I have no clue.

**Comment by kasperosterbye** [comment]
I have updated the examples - PR #334

**Comment by Ducasse** [comment]
Tx I lost patience with a strange bug... so I needed to take a break.
