### ISSUE TITLE
testIsOfflineAndResourceFound fails with different Morph height sizes

### ISSUE THREAD

**Issue by hernanmd** [pillar-markup/Microdown#354]
In a clean Pharo 9.0 with this installation:

```smalltalk
IceRepository registry 
	detect: [ :each | #('Microdown' 'NewTools-DocumentationReader') includes: each name ]
	ifFound: [ :aRepository | aRepository forget ].
"This, however, needs to stay :)"
#( 'BaselineOfMicrodownDev' 'BaselineOfMicrodown' 'Microdown' 'Microdown-Tests' 'Microdown-MicrodownRichTextComposer' 'Microdown-ResolvePath' 
'Microdown-ResolvePath-Tests' 'NewTools-DocumentationReader-Tests' 'BaselineOfNewToolsDocumentationReader'
'NewTools-DocumentationReader') do: [ :each | 
	(RPackageOrganizer default packageNamed: each ifAbsent: [ nil ]) 
		ifNotNil: [ :aPackage | aPackage removeFromSystem ] ].
	
EpMonitor disableDuring: [ 
	Metacello new
		baseline: 'Microdown';
		repository: 'github://pillar-markup/Microdown:master/src';
		onConflictUseIncoming;
		onUpgrade: #useIncoming;
		load ].
```

The method testIsOfflineAndResourceFound fails because it expects 133 but the image height of the anchored text form is 136. The same holds for testIsOfflineTrueAndResourceFound.

@kasperosterbye do you remember how did you obtained 133?

**Comment by kasperosterbye** [comment]
Very interesting @hernanmd. I have not at all looked at pharo 9 as Pharo 9 had its own Microdown, and I did not consider the backport of the current Microdown to Pharo9. 
Truth be told I obtained 133 by running the test - looking at the result in the inspector, verifying it was what was wanted, and hardwired 133.

**Comment by kasperosterbye** [comment]
Obsolete
