### ISSUE TITLE
MicFileResourceTest setUp uses on-line resources

### ISSUE THREAD

**Issue by hernanmd** [pillar-markup/Microdown#356]
The setUp method uses resource files (.md and .png) which can only be obtained through a connection.
These two resources could be generated using a memory file system and avoid connection requests during testing.

**Comment by kasperosterbye** [comment]
Indeed - I believe I am guilty of this test - and have grown wiser since.

**Comment by hernanmd** [comment]
No problem. A fix was already integrated using ByteArray as PNG and a readme textual method
