### ISSUE TITLE
Better align environments and extensions

### ISSUE THREAD

**Issue by guillep** [pillar-markup/Microdown#361]
- The && block could have an extension name + arguments
- The environment <? ?>  is not rendered by many rendereds such as github. Replace it by <! !> or make it an alias to it
- annotation ?{asd}? => {!asd?!}

**Comment by kasperosterbye** [comment]
Last two are done in #362 and #363

**Comment by kasperosterbye** [comment]
I'll take a look at this one now. It would be nice if all the extension mechanisms used the same extension principle, so I will see how much can be put into an extension trait.
