### ISSUE TITLE
Improve Microdown API for doing resolution

### ISSUE THREAD

**Issue by kasperosterbye** [pillar-markup/Microdown#384]
Extract from email between Stef and Kasper

### Stef:
I was wondering if we would not introduce an API at the level of microdown to avoid to have 
direct reference to MicZincPathResolver.
So we could have 

	Microdown >> resolveString: aString withBase: aBase
		
		| doc| 
		doc := self parse: aString. 
              MicZincPathResolver new 
			 absoluteReference: aBase  resolveDocument: doc. 
		 ^ doc

Let me know what you think.

### Kasper
How about a method in MicElement resolveFrom: aBase, changing the above method to:

	Microdown >> resolveString: aString withBase: aBase
		
		| doc| 
		doc := self parse: aString.
		 ^ doc resolveFrom: aBase

**Comment by kasperosterbye** [comment]
I completely misunderstood what you were saying @Ducasse. I fully agree there should be such a method in Microdown to avoid calling ZincPathResolver directly! And this facade should also be used in the tests.

**Comment by kasperosterbye** [comment]
I made a PR for this. I had a chat with @DelGaylord which cleared my mind regarding both the importance of the issue, and how to do it. 
In essence there is now a set of `resolveDocument: aDocument` methods:
- `'http://somewhere.fr/path resolveDocument: aDoc` (String uris - 'file:/path/to/my/file' works too, and assumes disk system - Sven fixed ZnUrl to allow 'file:/path' instead of 'file:///path' - yay @Ducasse ).
- `aZnUrl resolveDocument: aDoc`
- `aMicAbsoluteResourceReference resolveDocument: aDoc`
- `aFileReference resolveDocument: aDoc` (for example `FileSystem workingDirectory resolveDocument: aDoc`)

As well as `Microdown resolveDocument: aDoc withBase: base`, where base can be String, ZnUrl, MicResourceReference or FileReference

**Comment by Ducasse** [comment]
This is cool :)
