### ISSUE TITLE
testFileReferenceExtensionMethod in the test class MicFileResourceReferenceTest doesn't turn green on Windows

### ISSUE THREAD

**Issue by DelGaylord** [pillar-markup/Microdown#391]
When i load Microdown dev on my computer that on a Windows system, this test doesn't turn green

![ErrorOnWindows](https://user-images.githubusercontent.com/60885865/165701064-c06f24c5-d7ac-4814-85ad-5297cff80768.PNG)

**Comment by kasperosterbye** [comment]
I finally got my virtual windows to run again - and can confirm the error. I also know what is causing it, and will try to see if I can find a work-around.

**Comment by kasperosterbye** [comment]
PR #419 should fix this one.
