### ISSUE TITLE
MicFigureBlock has uncategorised methods

### ISSUE THREAD

**Issue by MarcusDenker** [pillar-markup/Microdown#417]
I am trying to have no uncategorized (see https://github.com/pharo-project/pharo/issues/9705)

In the image, MicFigureBlock is one of the last classes with non-categorized methods.

**Comment by kasperosterbye** [comment]
The issue is gone in the dev branch.

I am not sure when and how the elements in the dev branch is moved to Pharo11. 

@MarcusDenker @Ducasse - I could take on the task of maintaining the Pharo11/Microdown sync, but I need to be told about the policies and techniques for doing it.

**Comment by Ducasse** [comment]
Sorry but I do not have the time to deal with such issues.

S

**Comment by kasperosterbye** [comment]
@estebanlm
Looking through the baseline for Pharo, it seems like the integration of Microdown into Pharo is based on the 'integration' branch (naming makes sense).
The integration branch is rather behind the dev branch of Microdown.

I could merge the dev branch into the integration branch at times when the dev is stable.
However, I am not sure I understand the procedure for building Pharo well enough to "just do it". In particular -
- I cannot see how only the Microdown and MicRichTextComposer packages are built into Pharo
- From looking at the baselines of Pharo/Pharo11 and Microdown/integration it seems like the whole of microdown should be loaded (which fortunately does not happen ).

As I said above, I am willing to do the work of maintaining the integration branch of Microdown, but is not sure about the mechanism.

**Comment by Ducasse** [comment]
I do not remember but may be I did a special baseline or group to only load a minimal subset of microdown in P10.

**Comment by Ducasse** [comment]
I think that we should:
- add a tag (Pharo10, Pharo11....) for each released version of the integration branch, I guess that I did it
- then we can just merge master into integration and during P11 such versions will be taken 
- once P11 is released we just tag it as point 1

**Comment by kasperosterbye** [comment]
Seems like tagging and a special group (pharointegration or something similar) should solve the problems. Then the Pharo baseline need to be changed to only include that group. Then we can change the group on the Microdown end to control which packages are included into the Pharo image.

**Comment by MarcusDenker** [comment]
This is now fixed!
