### ISSUE TITLE
paragraph termination on <space><space><cr> not implemented

### ISSUE THREAD

**Issue by estebanlm** [pillar-markup/Microdown#438]
Hi, 

this is not a bug but a missing feature:  in markdown, there are two ways of ending a paragraph

1. empty line 
2. and two spaces at the end

so, markdown will parse:
```
paragraph1<cr>
<empty here>
paragraph2
```
and
```
paragraph1<space><space><cr>
paragrapho2
```
equally.

I guess we want the same for Microdown?

**Comment by estebanlm** [comment]
(I have a fix, if you think this is correct I will submit it)

**Comment by kasperosterbye** [comment]
I believe we should be compatible with github markdown unless there is a specific reason not to (like having extension mechanisms). So while I think it is an obscure rule, I think we should include it.

**Comment by Ducasse** [comment]
I would not. 
This is obscure so people should not use it. 
It makes bijective things obscure.

**Comment by kasperosterbye** [comment]
I agree with you @Ducasse that is is quite obscure.
But I think it should be implemented none the less, as it will allow us to better render documents already written for github.

**Comment by Ducasse** [comment]
I would also discourage people to use this. 
in HTML you should use a CSS class for this.
