### ISSUE TITLE
Table does not work well with nested | in monospace 

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#442]
Both following expressions produce the same output. 
```
Microdown parse: 'before  `\|foo bar ` after'.

Microdown parse: 'before  `|foo bar ` after'
```

In table

Microdown parse: '| Syntax expression | What it represents |
| --- | --- |
|  `|foo bar ` | second cell'.

Microdown parse: '| Syntax expression | What it represents |
| --- | --- |
|  `\|foo bar ` | second cell'

inlineParse: is 

```
inlineParse: aString
	| inlineParser childrenCol |
	inlineParser := MicInlineParser new.
	childrenCol := inlineParser parse: aString.
	childrenCol do: [ :each | each parent: self ].
	^  childrenCol
```

**Comment by kasperosterbye** [comment]
Yay - a cool bug!

**Comment by kasperosterbye** [comment]
I believe the first two:
```text
Microdown parse: 'before  `\|foo bar ` after'.

Microdown parse: 'before  `|foo bar ` after'
```
are as intended (if there ever was a consistent definition of intended). `\x`is translated into x, to allow \` to be written.

However, the translations of slash is not done consistently. 
I believe I know how to handle it consistently, but have not gotten around to doing it. 

I'll hack on this one now.

**Comment by Ducasse** [comment]
Cool. I'm checking that we can convert Pharo by example 9 and produce a nice PDF and I'm getting there :).

**Comment by kasperosterbye** [comment]
Now the first table gives (in rich text)
<img width="229" alt="image" src="https://user-images.githubusercontent.com/17723745/169689905-dc55da40-acd4-4ea0-abbb-65df239fa988.png">
and the second:
<img width="223" alt="image" src="https://user-images.githubusercontent.com/17723745/169689923-9ac2550e-e66b-4f05-bea5-bb391b0913a5.png">

PR coming up after lunch...

**Comment by kasperosterbye** [comment]
PR #447 fixes this
