### ISSUE TITLE
MathBlock should be $$ ... $$ and not &

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#452]
Now github supports math 
- https://github.blog/2022-05-19-math-support-in-markdown/.
- https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions

$$ for environment and $ for inline.

**Comment by Ducasse** [comment]
in addition this is a bit painful to see that they totally miss the parameter

### Working
$$
\left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right)
$$


# Not working 
$$
\left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right)
$$caption=This is a super cool formula&anchor=eq1

$$caption=This is a super cool formula&anchor=eq1
\left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right)
$$

$$
\left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right)
$$caption=This is a super cool formula 


$$
\left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right)
$$anchor=eq1

**Comment by Ducasse** [comment]
Oh this is nice. But what is sad is that the people in charge at Github are not thinking more. 
Now I integrated the change to $$ and all the tests passes

**Comment by kasperosterbye** [comment]
Fixed by #455 and #456
