### ISSUE TITLE
Problem with backslashes in math environments

### ISSUE THREAD

**Issue by olekscode** [pillar-markup/Microdown#46]
Backslashes `\` are very important in math environments, but Microdown removes them.
So they have to be escaped, which is very annoying and breaks the compatibility of Microdown math with standard LaTeX math.

For example, in LaTeX I would write
```TeX
$ f(a) = \frac{1}{2\pi i} \oint_{\gamma} \frac{f(z)}{z - a} dz $
```
and get this: 
![ComplicatedEquation](https://user-images.githubusercontent.com/8271691/86674380-ed2a7a00-bff8-11ea-9c29-b7e3adc93100.png)

But in Microdown it doesn't work:
<img width="1440" alt="Screenshot 2020-07-07 at 00 29 42" src="https://user-images.githubusercontent.com/8271691/86674468-003d4a00-bff9-11ea-84ed-f58d7c2ed58b.png">

What I have to do then is escape all backslashes. Like this:
```TeX
$ f(a) = \\frac{1}{2\\pi i} \\oint_{\\gamma} \\frac{f(z)}{z - a} dz $
```

Then everything is fine:
<img width="1440" alt="Screenshot 2020-07-07 at 00 35 26" src="https://user-images.githubusercontent.com/8271691/86674613-25ca5380-bff9-11ea-8231-65ed74052493.png">

But it would be great if backslashes were not captured in math environments.

**Comment by Ducasse** [comment]
Aie we did not thought about it. I do not know if the inline block logic. I will have to have a look but no time for now and laurine finished her internship.
