### ISSUE TITLE
Microdown comments that contain math environments are not rendered

### ISSUE THREAD

**Issue by olekscode** [pillar-markup/MicroDown#49]
Related to issue #41 
@Ducasse has fixed the baselines today, so now the Microdown can be installed properly in Pharo 9. And class comments are rendered correctly.

Except for the comments that contain math :(
Those ones do not render

![Screenshot 2020-07-07 at 16 56 54](https://user-images.githubusercontent.com/8271691/86800783-acbc1200-c073-11ea-9d04-f11ff80e19bd.png)

**Comment by Ducasse** [comment]
Yes the class was missing
