### ISSUE TITLE
When I execute tests I'm prompt for a github password :(

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#492]

**Comment by kasperosterbye** [comment]
For now, delete the browser tests. I will not be able to look at this for the next days.

**Comment by kasperosterbye** [comment]
Documents Browser that is

**Comment by Ducasse** [comment]
OK

**Comment by kasperosterbye** [comment]
I have not been able to reproduce this phenomenon. 
Do you have any hint to what scenario caused it to ask for github password?

**Comment by Ducasse** [comment]
I have the impression that it was due to the fact that gitlib was confused and could not find my token (that I had to change because it was an old one). So the connection failed and I got a prompt. 
I did not check recently.

**Comment by kasperosterbye** [comment]
Yes, I have run into that as well. I have an issue at Iceberg which is somewhat related: https://github.com/pharo-vcs/iceberg/issues/1590. I will close it here as it is not really Microdown related as such.
