### ISSUE TITLE
Extension points in microdown

### ISSUE THREAD

**Issue by kasperosterbye** [pillar-markup/Microdown#495]
# The MicMathBlock could/should be renamed.
This issue is just to capture my reflections on the extension points of microdown. 

## Paragraph extension
Microdown has three paragraph extension points
- MicCodeBlock ```` ``` ```` which one can extend with custom **stylers**. That is, the intended usage is that the body of the code block is styled (typically coloured), and the body is not treated as microdown (is not parsed).
- MicEnvironmentBlock `<!...!>` is intended for making custom markdown by subclassing MicEnvironmentBlock, tagging and MicArgumentList to concert the instantiation of the extension. The body of this block is treated as microdown and is parsed.
- MicMathBlock (was recently changed from `&...&` to `$$...$$` to stay compatible with github markdown). Math block has been designed to do latex math, hence its name. However, is an extension point as latex is merely the default. The body of math block is not intended to be parsed by microdown but latex. The output is not intended to be just coloured, but completely transformed (for Latex into an image of the formula).

### plantuml
I have a small extension which allow the conversion of [plantuml](plantuml.com) into an image. If I have to pick one of the three extension points available in microdown, I write it as:
```text
$$plantuml
plantuml script
$$
```
I pick the math block because the body should not be parsed (it is not an environment block), and the text is transformed, not styled (it is not a code block).

### raw
We have an open issue (#436) about a mistaken use of the **inline** raw block. Raw is not expected to parse its body, so it is not an environment. Code blocks are formatted in a uniform manner besides being styled. Mathblock does not parse, not style, and raw can be obtained by and extension of math block as:
```text
$$raw
raw stuff goes here
$$
```

### multi line comments
Same arguments as for raw:
```text
$$comment
my lovely comment 
goes here
$$
```

**Comment by Ducasse** [comment]
I want to improve the class comment to mention such difference.

**Comment by kasperosterbye** [comment]
See discussion in #553

**Comment by kasperosterbye** [comment]
I close this one as #553 is more resent
