### ISSUE TITLE
MicTableBloc does not work in comments!

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#50]
To debug

```
renderComment: aString of: aClassOrPackage 

	| builder |
	builder := MicroDownParser builder.
	aClassOrPackage buildMicroDownUsing: builder withComment: aString.
	self flag: #fixMe.
	"I do not like the asText: the interaction between parser, richtext composer should be 
	more obvious"
	"^ [ MicroDownParser asText: builder contents ] on: MicParsingError, MessageNotUnderstood, SubclassResponsibility  do: [ builder contents  ]"
	
	^ MicroDownParser asText: builder contents
```

Support table with a simple and more relax setup than github.
A table is not forced to have a header definition.

| aaab | jkhjh |
| --- |
| bar |

or 
|aaab|jkhjh|
|---|
|bar|

or 
| aaa | bbb |
|ccc |ddd |

or 
| aaa | bbb
| cc | ddd

Block-level elements cannot be inserted in a table.

When a table contains a header it is the first row and all rows should have that size else they are cut. 

Known limits: how to put a pipe in a table? 
No support for \|

**Comment by kasperosterbye** [comment]
After PR #237 tables now render in Text, and hence also in class comments.

This is many issues - not just one - but let me comment on each
* Syntax - I think is it fine to leave the syntax as it is - microdown is said to be simpler than markdown, this suggest to just keep what can be parsed now.
* One cannot insert block-level elements into a table. That is actually a very interesting observation. What comes to mind as a possible solution is a special bracket construct which makes can encapsulate blocks and make them an inline block. It will require a hack in the parser.
* Letting the size of the header elements decide the width of columns is quite possible, but then one will immediately start looking for how to generate white-space to make the columns wider. As it is currently implemented, the width is the maximum of the elements in the column. 
* It should be doable to let the pipe symbol be \I - I believe the machinery for that exist already, but has just not been applied here.

**Comment by kasperosterbye** [comment]
I extracted two more issues from this one (#277 and #278), and close this one as done.
