### ISSUE TITLE
LoadMicrodown methods for MicRelativeResourceReference missing

### ISSUE THREAD

**Issue by DelGaylord** [pillar-markup/Microdown#500]
So to explain i try to convert a Microdown file with an inputfile on it in order to see if it works with the class MicFileIncluder but with this script it give me this error which i think when i check the implementors that we lost the method for the MicRelativeRsourceReference.
Here the code: 
![image](https://user-images.githubusercontent.com/60885865/176886066-7f8ac001-b7ec-4aec-96b7-dc562c3c6d38.png)
And here the error:
![image](https://user-images.githubusercontent.com/60885865/176886139-dd81392c-3d07-4f98-a038-c9fbc90cccdb.png)

**Comment by kasperosterbye** [comment]
I will try to look at this Monday

**Comment by kasperosterbye** [comment]
A relative reference cannot load a file, as a relative reference need to be resolved to an absolute before it can be loaded, sort of like you can not enter the "town hall" if you do not know the city.

Besides, if you use an absolute file reference, 
```smalltalk
fileRef : = FileSystem disk root / 'D: \Bureaubis\ToDebugConversionPharoWithstylelindex.md'
ref := fileRef MicFileResourceReference.
ast := ref loadMicrodown.
output := MicSBALaTeXWriter new visit: ast.
```
`loadMicrodown` will resolve all relative references in the document with respect to absolute document in `ref`, and the above script should work (have not tried it).

**Comment by Ducasse** [comment]
thanks kasper.
