### ISSUE TITLE
FileIncluder should get the tests of MicInputFileResolver and remove MicInputFileResolver

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#515]
Merge MicInputFileResolver into FileIncluder (if this is the correct move) 
but start to migrate test of MicInputFileResolver. 

S

**Comment by DelGaylord** [comment]
I have work on that and made a PR so you can check if this is ok. I have not added all the tests because some was the same in the two class but i have replace the use of nextPutAll: by the use of a builder.

**Comment by Ducasse** [comment]
Tx Gaylord
