### ISSUE TITLE
Logic of <! khjkhjjk !> is not robust enough

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#521]
We should make sure that it works for

```
<!inputFile|path=blblbl !>

<!inputFile|path=blblbl!>space
```

**Comment by kasperosterbye** [comment]
I have been thinking about making some changes to MicArgumentList:
* The first element (up to | ) must be a single word
* Allow the | to be optional if there is no further parameters, and moving the rest of the line into body
* Trimming the value (between = and & or end)

To accommodate different usage scenarios, I might implement messages to "normalise", especially item 2 and 3, so it is up to the specific block to decide on the details.

**Comment by kasperosterbye** [comment]
I had not realised, but this is actually two issues in one.
1. `<!env...!> bla` breaking
2. `<!inputFile|path=pathToMyDocument.md   !>` should be trimmed.

PR #522 seems to address 1. And 2. for the last argument.

I recommend accepting #522 as it is an improvement overall.

**Comment by kasperosterbye** [comment]
It has been fixed
