### ISSUE TITLE
MicRelativeResourceReference uri does not work correctly!

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#527]
if I have a relative reference, when I asked it uri I get a leading slash so I cannot convert easily a relative reference to a relative reference.

```
'figures/foo.png' asMicResourceReference uri
> /figures/foo.png
```

:(

In fact I hate ZnUrl usage. 

Now not using uri in uriBlock: 
```
	urlString := aMicUrlBlock reference uri asString.
```
=> 
```
	urlString := aMicUrlBlock reference path.
```

Does not work for 

```
'http://pharo.org/figures/foo.png' 
```

I'm thinking that I should have down a parser of file path and control everything. 

```
urlBlock: aMicUrlBlock
	
	| queries urlString |
	self halt.
	queries := aMicUrlBlock reference uri query.
	aMicUrlBlock reference uri query: nil.
	"UGLY we remove the query dicrtionary just to print."
	urlString := aMicUrlBlock reference uri asString.
	aMicUrlBlock reference uri query: queries.
	^ aMicUrlBlock associatedPillarClass new
		  setChildren:
			  ((aMicUrlBlock inlineParse: aMicUrlBlock substring) collect: [ :n | 
					   n accept: self ]);
		  reference: urlString;
		  yourself
```

**Comment by kasperosterbye** [comment]
Hi

The things you need are there, but it seems like they are hidden.
> 'figures/foo.png' asMicResourceReference uri
'figures/foo.png' asMicResourceReference path >>> 'figures/foo.png’

( Microdown parse:'[Foo](/anUrl)' ) children first children first reference path >>> '/anUrl'
( Microdown parse:'[Foo](file:/anUrl)' ) children first children first reference path >>> '/anUrl'
( Microdown parse:'[Foo](file:///anUrl)' ) children first children first reference path >>> '/anUrl’

Hope this help!

I believe the core is in need for a cleanup, and in particular many of the methods seems to be in need of comments .

Best,

Kasper

**Comment by Ducasse** [comment]
Hi Kasper
Thanks it help.
I will turn this into tests.
I was in the mode to understand fullName to MicResources.
I will check also to the user of uriString because they are introducing more problems that anything else. 
And yes I think that the API should be tightened up. 
For now I would like to be able convert a full book because we have around 20 books to migrate.

**Comment by Ducasse** [comment]
I think that we will have to revisit relativePath too.

Now I will use path but it is not working well for 

```
'http://pharo.org/figures/foo.png' asMicResourceReference path
>>> /figures/foo.png which looks wrong to me

and not 'http://pharo.org/figures/foo.png'.
```

**Comment by kasperosterbye** [comment]
While there are many similarities between file: and http: (and comment: github: source:,...), some of the details definitely have the feel of "I need this method for my code to run" rather than a feel of solid design. I know I am guilty of that here and there.

The main reason I want to use ZnUrl for the resolution is because it implements resolution - in particular including
- `.`, `..`
- queries on the main document `http://foo.org/path/mydoc.md?aaa=bbb` and relative `img/logo.png` gets combined into `http://foo.org/path/img/logo.png?aaa=bbb` as it must according to the standards.

In the concrete case about path, it seems like we need either:
- override path to return `/path` for files, and `path` for http.
- let file references implement a dedicated method `rootedPath` or `fullPath` or what ever is the right name for one that returns `/path`.
- something other I did not think of

**Comment by Ducasse** [comment]
I'm trying to see if we can get fullName to play this game. 
I will analyse the uriString and uri usage. I would like uri to be internal and not expose.
So I will try to see if I can get the converter working and all the tests green.

**Comment by kasperosterbye** [comment]
> I'm trying to see if we can get fullName to play this game.
> I will analyse the uriString and uri usage. 

My guess is:
```smalltalk
MicFileResourceReference>>#fullName
	^ '/',uri path
MicHTTPResourceReference>>#fullName
	^ uri path
```
> I would like uri to be internal and not expose.

Yes, I agree

I will be able to find time to get this mess fixed Saturday. If you just write the specs for file and http. I know this code rather well, and you should get those books done!

**Comment by Ducasse** [comment]
I'm trying to adapt all the tools to work but flo is arriving from a 11 hours trip so she will be dead and I will need to be present. 
I have to check the changes I have in my image. 
Basically I need a way to have a file display as (nofile://) and an http:/.... as http:/ 
and this for dynamic/unresolved or not. 
Then I will fix all the senders of uriString, path to only use one protocol.

**Comment by kasperosterbye** [comment]
something like this?
- (relative) 'img/foo.pdf' -> 'img/foo.pdf'
- (absolute file) '/User/Asterix/Chapter1/chapter1.md' -> '/User/Asterix/Chapter1/chapter1.md'
- (absolute http) 'http://files/Chapter1/chapter1.md' -> 'http//sowhere.org/files/Chapter1/chapter1.md'

Are there any other scenarios?

**Comment by Ducasse** [comment]
I succeeded to have all tests green with fullName
[DelGaylord/feature/filePath](https://github.com/pillar-markup/Microdown/tree/DelGaylord/feature/filePath)
Now I'm investigating uriString and adding more tests.
Then I will check the converter

**Comment by Ducasse** [comment]
So I cleaned a lot. 
Now I got problems because some github tests are trying to connect to github and may be we should turned them as mocks.
Anyway I will continue later and I'm going in the right direction

**Comment by kasperosterbye** [comment]
It is unclear if this one is actually closed @Ducasse

**Comment by kasperosterbye** [comment]
Then we close it. If there is a problem it can be reopened, or a new issue raised.
