### ISSUE TITLE
MicCodeStylerSpec class>>codeStylerFor: (bobby is Undeclared)

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#538]
NewUndeclaredWarning: MicCodeStylerSpec class>>codeStylerFor: (bobby is Undeclared)
[252](https://github.com/pillar-markup/Microdown/runs/7827895013?check_suite_focus=true#step:4:253)
NewUndeclaredWarning: MicCodeStylerSpec class>>codeStylerFor: (blue is Undeclared)

I do not know why the build does not pass then.

**Comment by kasperosterbye** [comment]
This is not a Microdown issue per se, the compiler writes this message to transcript each time one try to compile a method with an undeclared variable.
Syntax highlighting calls the compiler.
And there are two tests whose purpose is to make sure that undeclared variables and messages are not highlighted in red. 

If this needs to be fixed, I will need guro help.
