### ISSUE TITLE
Agenda visitors need to be defined as extension methods to MicrodownVisitor

### ISSUE THREAD

**Issue by kasperosterbye** [pillar-markup/Microdown#539]
These visit methods need to be defined as extensions:
<img width="128" alt="image" src="https://user-images.githubusercontent.com/17723745/185051437-03d6c1c6-b1ff-4222-9fda-184ecd3e2256.png">

If not existing methods will break if presented with a document using these extensions.

@DelGaylord - Before making a PR it is important that you run some tests, especially now that the CI is broken. I use the TestRunner:
<img width="321" alt="image" src="https://user-images.githubusercontent.com/17723745/185052384-b2ab20b9-b81b-4b8a-81d2-39a2d1ed7a9f.png">
And run all Microdown Tests - notice the filter in the upper left corner:
<img width="770" alt="image" src="https://user-images.githubusercontent.com/17723745/185052513-ad7a9d77-389f-41cf-94e8-58053d8db5f5.png">

If you want to be really thorough, you can run the `Release tests too, but they take a long time and can be hard to see if the blame is on your code or not. I only do that rarely.

**Comment by kasperosterbye** [comment]
It is not super hasty, but need to be done before Agenda is included in the Baseline

**Comment by DelGaylord** [comment]
Thank you for your comments @kasperosterbye, i am sorry to not have checked correctly the tests but i have done this PR the last day of my internship. I am currently checking this and correcting my mistake, i will ensure to now recheck the tests before making a PR

**Comment by kasperosterbye** [comment]
👍 Glad to help you learn something also on your last day 😎

**Comment by DelGaylord** [comment]
I have made a PR which will made all the tests green by adding the methods to MicrodownVisitor and letting the responsibility to the subclasses
