### ISSUE TITLE
Should Math block be renamed to Script block?

### ISSUE THREAD

**Issue by kasperosterbye** [pillar-markup/Microdown#553]
Math block ($$) was originally designed for math.
The three extension blocks in Microdown are environment (<!...!>), codeblock (```), and Math ($$). 
My suggestion is that we rename MathBlock to ScriptBlock, as it easier to understand.
$$roassal
$$plantuml
$$pharo
$$latex (default)

**Comment by Ducasse** [comment]
I understand your idea to have DSL inside and I was wondering if we could not have another node

$$latex (default) => math

scriptBlock
$!roassal
$!plantuml
$!pharo

Because the script block will be to many things and I would like to be able to avoid to have complex conditional logic. 
We could have 
<!..!> where nested elements are microdown
``` = verbatim
$* $$ latex interpretation $! would be script

**Comment by kasperosterbye** [comment]
Ahh, latex is default, so if you do not write anything, like:
\$$
2+3
\$$
It is the same as writing
\$$language=latex
2+3
\$$
Also, writing 
\$$foo
is the same as 
\$$language=foo

But we are of cause free to add even more syntax nodes :-)

**Comment by kasperosterbye** [comment]
All the above is part of the standard functionality of the MicArgumentList.

**Comment by Ducasse** [comment]
Sure. In fact for me the problem is not the written part but the behavior. 
For example in pillar [[[]]] was overloaded with test, eval, ... and it started to be messy

**Comment by kasperosterbye** [comment]
I understand, for instance I am never able to remember if inputFile is rather inputfile, or if the argument is path or url.

For microdown, I follow the idea of staying compatible with github unless there is a strong reason not to.

So, regarding $$, I would actually rather reserve that for math/latex only, and use ```foo for everything else. 

That will lead to the mess you mentioned regarding [[[]]], but I think the answer to that is to make the documentation accessible. 
One option is to insist that all such extensions have a help text, and ```foo|help inserts the help rather than the body. Also, a test can be made to ensure that all extensions has a help text. 

So - I will suggest to revert to $$ being math only, and having only two block extensions - <! and ```.

**Comment by Ducasse** [comment]
ok for math
Now what would be good is to be able to have a way to extend the treatment of the body of ```
because for <! this is clear that we will have extra nodes.
I was thinking about a kind of MicInternalBodyCodeBlock (and subclasses) so that we can delegate to it and get it modular. Because right now in Pillar this is difficult to have some [[[ behavior separated from the base behavior.

**Comment by kasperosterbye** [comment]
Some kind of refactoring would be good. At the moment the MicCodeBlock is not set up for extensions. 

I will suggest to keep the name MicCodeBlock for what it does now, to add a sister class MicScriptBlock to do plantuml, scripts, roassal etc, and give the two a common anchestor MicAbstractCodeBlock which provides access to the text body and MicArgumentList etc.

**Comment by Ducasse** [comment]
I was not thinking to change the name of the class but that this class creates an internal node to which we can delegate.
We could have a way to get the correct innerBody given a tag

For example we could get the test

```language=tester
1 + 2 
>>> 7
``` 

and this code block would have an instance of MicInternalCodeBlockTester (subclass of MicInternalCodeBlock).

**Comment by Ducasse** [comment]
OK I see your customization hook would be in the parser that would generate subclasses of MicAbstractCodeBlock.
I'm also thinking about the impact on the visitor. If I think correctly with my approach (the new inner node) the visitCodeBlock would delegate to it and we would have to define a new accept method in the inner code + visit
With your design we would have just a visitScript: now I would like to see how I can map the test behavior of pillar (because I would like to be able to test the documents).

**Comment by kasperosterbye** [comment]
I am running through the issues and assigning labels. I see there is a related issue #540, which would bring these discussions together.

It would be extremely helpful for me to get a pointer to some of these advanced things you did in the pillar books. I have never seen them, and I am just guessing.

**Comment by Ducasse** [comment]
Yes I was currently checking pillar just for that scenario :).
Now lectures starts

**Comment by kasperosterbye** [comment]
I would like to finalise this one. Based on the discussions above I would summarise as:
- \$$ is for math only
- \``` will be used for both styling and extension scripts. It will use a tag based subclass extension mechanism similar to that of environments and annotations.
- The idea of keeping code highlighting and scripting separate will be done by MicAbstractCodeBlock as superclass of MicCodeBlock (existing class - intended for highlighting only), and MicScriptBlock (new class - script based generation of document).

**Comment by Ducasse** [comment]
Me too. 
Now what is the status of <? ?> in the extension story?
We could also have a new syntax not to overload ```.
But I think that having an extensible ``` can be the right solution

**Comment by kasperosterbye** [comment]
I am not 100% sure I know what you mean by "extension story", but extension will then be in two formats:
- environments, where the body of the environment will be parsed as microdown
- Code blocks, where the body is raw text, but typically preprocessed before presentation

As of extra syntax - I happen to disagree :-)
The above usage of \``` is compatible with how github also unify formating and scripted contents (github now support using a uml diagram tool called mermaid similar to plantuml).

**Comment by kasperosterbye** [comment]
In any case, I will start on this, and we can add extra syntax later.
