### ISSUE TITLE
Code highlight is unreadable in Dark theme

### ISSUE THREAD

**Issue by jordanmontt** [pillar-markup/Microdown#557]
For example, let us look at this code, from a class comment, that is shown in Calypso:

![Capture d’écran 2022-09-23 à 14 17 51](https://user-images.githubusercontent.com/33934979/191958377-2e6815b6-2cae-46e5-bc5b-3ce09e769a9e.png)

**Comment by kasperosterbye** [comment]
Cool bug - the standard styler is used, but seems not to be told the theme.
