### ISSUE TITLE
MicMathInlineBlock comment does not render

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#567]
Strange but it looks like it is broken.

**Comment by kasperosterbye** [comment]
Cool bug! Turns out the problem is unrelated to math, but is in the monospace block. 
This is the minimal failing expression '\`\a\b\`'.
I will look at it over the weekend.

**Comment by kasperosterbye** [comment]
This one is really really very very nasty!
The inline parser assumes its substring length to be stable, but it is not when there is backslash handling.
I remember I ran into the issue earlier, and did a different backslash handler. But the actual error is elsewhere, and it is unclear where to fix the problem as the inline parser is so convoluted (imho).
The the thing is that a in monospace (and math) a string can get shorter. For instance '$he has many\$ in his pocket' is one character longer than its final substring ('he has many $ in his pocket'). Thus the start and end indexes end up being wrong.
I will still spend some time trying to find out of there is a place to fix it.

But it might be faster to rewrite the entire inline parser...

**Comment by Ducasse** [comment]
Yes I hate the inline parser and its logic and the way the tokens are managed.
