### ISSUE TITLE
"Save" button in PEAR raises an exception

### ISSUE THREAD

**Issue by olekscode** [pillar-markup/Microdown#59]
Steps to reproduce:
1. Create a new Pharo 9 image
2. Open _Tools > Pear_
3. Press _"Change input syntax"_
4. Press _"New"_. You will get an empty editor
5. Type some Microdown text
6. Press _"Render"_. You should see the correctly rendered output on the right
5. Press _"Save"_. And BOOM!

![Screenshot 2020-07-21 at 13 06 36](https://user-images.githubusercontent.com/8271691/88048189-2ca5aa00-cb53-11ea-84bb-e564a85e9373.png)

**Comment by LaurineDargaud** [comment]
Maybe the following package is missing in baseline: [file-dialog from Ducasse](https://github.com/Ducasse/file-dialog)
Install it then retry

**Comment by kasperosterbye** [comment]
Pillar has been superseded by Microdown. The problem is not reproducible in the final image of Pharo 9.
