### ISSUE TITLE
Rendering the class comment of MicHTMLStyler produces an error for keyword

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#597]
Rendering the class comment of MicHTMLStyler produces an error for keyword.
To reproduce change the settings to not capture error.

```
initialTextAttributesForPixelHeight: aNumber
	"Render undefined same way as defined"
	"Perhaps this is not the right spot to hook into stuff, but it seems to work"
	| dict |
	dict := super initialTextAttributesForPixelHeight: aNumber.
	dict at: #undefinedIdentifier put: (dict at: #instVar).
	dict at: #undefinedKeyword put: (dict at: #keyword).
                                                                ^^^^^^^^^^^^^^^
	dict at: #undefinedBinary put: (dict at: #binary).
	dict at: #undefinedUnary put: (dict at: #unary).
	^ dict
```

**Comment by kasperosterbye** [comment]
In `MicParsesAndRendersAllCommentsTest>>#testSmokeSignalAndChoke` is a test that tries all class comments in the entire system (not run as part of CI as it is too big).
It fails. It fails because the changes to tab-semantics to allow indentation of code and environments seems not to be robust.
