### ISSUE TITLE
Feature request: Keyboard shortcuts in PEAR

### ISSUE THREAD

**Issue by olekscode** [pillar-markup/Microdown#60]
When writing text in the editor, it is really handy to have keyboard shortcuts for the basic operations such as "Save" and "Render". However, I think that other options should be supplied with shortcuts as well ("New", "Open" etc.)

Why is it important:
1. It saves time
2. It makes sure that you don't lose your thought when you write
3. It encourages to Render and Save often

The standard editor shortcuts Ctrl+S, Ctrl+N, Ctrl+O, Ctrl+T (Cmd+S, Cmd+N, Cmd+O, Cmd+T) are already used in Pharo.
I don't know if it's possible to redefine them for the case when PEAR window is in focus.
If yes - that would be great!

**Comment by kasperosterbye** [comment]
The PEAR tool is not in the final image of Pharo9.
