### ISSUE TITLE
"Change input syntax" in PEAR does not translate the input

### ISSUE THREAD

**Issue by olekscode** [pillar-markup/Microdown#61]
I would expect the _"Change input syntax"_ button in PEAR to translate between Pillar and Microdown. But it doesn't do that.
Instead, it deletes the text that was written in the editor and replaces it with a default Pillar or Microdown example.

So in fact, _"Change input syntax"_ does what _"Get example"_ should be doing

**Comment by kasperosterbye** [comment]
Obsoleted

**Comment by kasperosterbye** [comment]
Obsoleted
