### ISSUE TITLE
Feature request: Show warning before removing the unsaved text in PEAR

### ISSUE THREAD

**Issue by olekscode** [pillar-markup/Microdown#62]
Here are some situations when everything you were writing can be gone:
1. Close Pear window
2. Press _"New"_
3. Press _"Change input syntax"_
4. Press _"Show example"_

It would be nice to show a warning in those cases: _"If you leave before saving, your changes will be lost."_
This issue is not critical, because in cases 2-4 you can still press Ctrl+Z and restore what you were writing

**Comment by kasperosterbye** [comment]
Obsoleted
