### ISSUE TITLE
crAfterHeader: -> DNU

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#630]
Now in latest P11 run the loading script (i.e. removing the existing packages) and loading dev
when I execute the tests I get an error with truncateTo:

crAfterHeader: spacingSpec
	"spacingSpec is a series of numbers 2;2;1;1 - which is the number of new lines to be added 
	after headers of level1, level2 etc. 1's at the end can be omitted (2;2;1;1 is the same as 2;2)"
	|spacings|
	crAfterHeader := #(1 1 1 1 1 1) copy. "copy to get non-literal"
	spacings := ((spacingSpec splitOn: ';') truncateTo: 6) collect: [ :spec |spec asNumber ].
	spacings doWithIndex: [ :elem :index |crAfterHeader at: index put: elem ]

**Comment by kasperosterbye** [comment]
Strange how that method has been lost.
PR coming up.

**Comment by Ducasse** [comment]
may be during the renamed of the package.
Mayu be we should push it to Pharo P11.

**Comment by kasperosterbye** [comment]
we might do that. 
It is actually defined in String in a manner where it can be raised to OrderedCollection (maybe even SequenceableCollection) without changing the code.
