### ISSUE TITLE
Math not working

### ISSUE THREAD

**Issue by olekscode** [pillar-markup/Microdown#642]
I tried to build a PDF from Microdown with a simple math expression:
```
$$
x_{t+1} = x_{t}+r_{x_{t}}(1 - \frac{x_{t}}{k})
$$
```
But it does not work.
So either, I am defining math with a wrong environment or something is broken in Microdown

### Example

This block of math:
https://github.com/cormas/Booklet-CORMAS/blob/master/Chapters/CORMAS/chap_ecec/ECEC-Model.md#the-plants

Is not compiled (p. 25 of the PDF):
https://github.com/cormas/Booklet-CORMAS/releases/tag/latest

**Comment by Ducasse** [comment]
Fixed
