### ISSUE TITLE
codeblock arguments should be clarified

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#67]
In markdown we can write

` ` `smalltalk

 1 + 2

` ` `

while in microdown we favor

` ` `language=smalltalk

  1 + 2

` ` `

We should write tests for this.

**Comment by kasperosterbye** [comment]
Done in Kanban - does it mean this should be closed?

**Comment by Ducasse** [comment]
I do not remember. 
I'm sure that we have tests for the second case now. 
And I do not think that we have to support the first one.
