### ISSUE TITLE
Do not use deprecated #next of UUIDGenerator in MicHTMLDocument>>#tempFileName

### ISSUE THREAD

**Issue by astares** [pillar-markup/MicroDown#679]
In MicHTMLDocument>>#tempFileName

we should use

```Smalltalk
UUID new asString36
```

instead of 

```Smalltalk
UUIDGenerator new next asString36
```

for Pharo 12

**Comment by Ducasse** [comment]
Done

**Comment by astares** [comment]
Thanks. 

For the records: https://github.com/pillar-markup/Microdown/blob/Pharo13/src/Microdown-HTMLExporter/MicHTMLDocument.class.st

**Comment by Ducasse** [comment]
You mean that it is also fixed there?
For now I will not merge back Pharo 13 in dev because I'm not developping in P13.
I have to release a new version with correct tags because now more recent ones are 2.5.x and not 2.6.0 is making a mess in the numbering.
