### ISSUE TITLE
Cannot attach Microdown to Pharo 12 because of Iceberg error

### ISSUE THREAD

**Issue by hernanmd** [pillar-markup/MicroDown#681]
## How to reproduce

- Clone this repository into a local directory
- Open latest Pharo 12
- Open Iceberg -> System -> Microdown -> Repair
- Select local directory
- Red screen of death in the Repositories window

<img width="1440" alt="Screenshot 2024-01-29 at 15 06 56" src="https://github.com/pillar-markup/Microdown/assets/4825959/00dbacf0-3b90-4895-b62c-3281d2aeb998">

**Comment by Ducasse** [comment]
I do not think that this is related to microdown but more related to iceberg

**Comment by hernanmd** [comment]
Ok, I opened an [issue in Iceberg](https://github.com/pharo-vcs/iceberg/issues/1803) so this can be closed here.
