### ISSUE TITLE
Browsing comment of RBPatternVariableNode raises a syntax Error?

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#72]

**Comment by Ducasse** [comment]
I can parse the comments.... so I do not get the rendering generate a parse error.
Need to be investigated more

**Comment by kasperosterbye** [comment]
As of 2021-11-07 this error is still present if using BeautifulComments from master branch.

BeautifulComments should be robust to any error - a possible way is to simply use the string version in case of any error.

The error is lack of generality of `MicRichTextComposer>>visitMonospace:`, which creates a MicSemanticAction.

```smalltalk
MicSemanticAction>>from: aString
   from: aString 
	^ self fromTokens: (RBScanner scanTokens: aString)
```

If the monospace is not syntactially correct pharo syntax `RBScanner` will fail.

In case of the comment in `RBPatternVariableNode` there is an unmatched `"`.

The visitMonospace: method is flagged at problematic already.
