### ISSUE TITLE
ConfigurationCommandLineHandler not existent anymore (in P12/P13)

### ISSUE THREAD

**Issue by astares** [pillar-markup/MicroDown#754]
- use Pharo 13
- load the project from "Pharo13" branch

```Smalltalk
Metacello new
	baseline: 'Microdown';
	repository: 'github://pillar-markup/Microdown:Pharo13/src';
	onConflict: [ :ex | ex useIncoming ];
	onUpgrade: [ :ex | ex useIncoming ];
	load.
```
This gives you the code that is loaded in Pharo 13

- run the test MicParsesAndRendersAllCommentsTest which fails as "ConfigurationCommandLineHandler" is not existing anymore

 
![Screenshot from 2024-05-28 14 36 17](https://github.com/pillar-markup/Microdown/assets/5980033/ed8125c2-aaa1-4fc0-8823-1ad870f1e851)

**Comment by astares** [comment]
We should remove this test as it makes no sense.

"Microdown" project is unfortunately not managed so well like other projects and would require some love. I think adding CI would be a nice step so these topics will be found earlier.

**Comment by Ducasse** [comment]
Please note that the development of Microdown is happening in Pharo 12. 
And the development of Microdown is following its own roadmap.
