### ISSUE TITLE
Unhandled metadata parsing error

### ISSUE THREAD

**Issue by Gabriel-Darbord** [pillar-markup/MicroDown#760]
Reproduce it by running the following minimal example:
```st
Microdown parse: '{'
```

The problem is with `MicMetaDataBlock >> #closeMe` which fails when the body is `nil`.
The expected error handling is to go into bogus parsing mode and still return a block.

**Comment by Ducasse** [comment]
Thanks.
I'm not sure that catching Error but I understand the idea.

**Comment by Gabriel-Darbord** [comment]
I agree that the fix is not too great.
In the given example, the body was nil, but I didn't see a way to handle that and avoid messy code.
And there may be other errors that have not been found yet.
