### ISSUE TITLE
Latex support for math should be revisited

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#79]

**Comment by kasperosterbye** [comment]
What issues in particular do you have in mind?

For my part, I am not happy about the extra non-github markup. I would rather hijack existing markup. An inlined latex formula could be written as:
`![\\frac{C_1\cos(\theta_i+C_3)}{C_4+C_1\cos(\theta_i+C_2)}](#!latex)`. In github this would render as:

![\\frac{C_1\cos(\theta_i+C_3)}{C_4+C_1\cos(\theta_i+C_2)}](#!latex)

and in image we can make "urls starting with a `#!`" do something extra in the `closeMe` - to get the latex image:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/17723745/133087454-ed1dc01c-33f9-4f6d-a054-5c1f94a1d7c3.png">

I am not particularly in favour of `#latex`, anything but special non-github markdown is fine by me.

**Comment by Ducasse** [comment]
We should check the LaTeX exporter. and for the HTML version we can emit JMath or something like that.

**Comment by Ducasse** [comment]
I'm not found of overloading images because then the code of the visitor will be full of cases. 
We took a nice syntax for math in text and math environment. 
This is important because this way we can support equation label and anchor as done in latex in a way that is similar to code block and figures (e.g., ?anchor=foo&width=80)

**Comment by kasperosterbye** [comment]
OK - your original issue really become how to handle it in the different (RichText, Latex, HTML) builders. 
I guess math renders in Latex and RichText at the moment, and there is no HTML builder at the moment.

**Comment by Ducasse** [comment]
There is package for the LaTex exporter but it needs love because it generates broken latex. 
Because leo did not know latex.

**Comment by kasperosterbye** [comment]
Seems fixed
