### ISSUE TITLE
Make sure that GT kind of comments should not break the rendering.

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/Microdown#82]

**Comment by Ducasse** [comment]
May be a class could determine the comment parser... but this is too complex.

**Comment by kasperosterbye** [comment]
What class has a GT kind of comment (I ask because I do not know what a GT kind of comment is)

**Comment by Ducasse** [comment]
In fact none in Pharo but in Bloc. But feenk abandoned the Pillar comments. 
So I think that we should just make sure that we capture exceptions if they are raised browsing comments.
