### ISSUE TITLE
the bookchecker does not report on figure with files that do not exist.

### ISSUE THREAD

**Issue by Ducasse** [pillar-markup/MicroDown#884]
```
![blue %width=30](figures/pharo2DOESNOTEXIST.png )
```

is not reported as a problem in the reference checker

**Comment by moufort** [comment]
I see you pass the issue to Yasser, i has started to work on, I can share my work with him.
I just wonder if this issue is not the same than issue #873 and issue #814

**Comment by Ducasse** [comment]
Quentin if you can finish then this is good too. Let me know.
