### ISSUE TITLE
Cannot load latest release: Load shows 120 resolvable conflicts 

### ISSUE THREAD

**Issue by riuttner** [pillar-markup/MicroDown#903]
When trying to load latest release for P13 via Pharo Launcher with my baseline containing
```
	spec
		  baseline: 'Microdown'
		  with: [ spec repository: 'github://pillar-markup/Microdown:Pharo13' ]
```
I end up either with a debugger missing an extension on class side (Class>>#buildMicroDownUsing:withComment:) or I can choose the "merge" option which cannot be performed due to 120 unresolvable conflicts 
(window title: "Merging Microdown-Tests-CompatibleUsername.1730027614").

I would guess that the latest commit (shown as having happened today about 4 hours ago) broke something important.

My last image build based on the same Microdown baseline about 2 weeks ago worked without any issue.

**Comment by Ducasse** [comment]
Pay attention before loading microdown you should execute the script (see the workflow). 

```
removeCleanlyMDAndBC

	<cozyScript: #'Flush MD and BC'>
	#( 'Microdown' 'BeautifulComments' 'DocumentBrowser' ) do: [ :name |
		(IceRepository repositoryNamed: name)
			ifNil: [ self inform: 'Project not found: ' , name ]
			ifNotNil: [ :found |
				found
					unload;
					forget ] ]
```

**Comment by Ducasse** [comment]
I never tried to load microdown without unloading microdown and its clients from Pharo. 
So I do not know if it is working.

**Comment by Ducasse** [comment]
I'm coding in P13 and it loads like that

**Comment by riuttner** [comment]
Many thanks, worked for me!

I added your lines at start of my launcher initialization script such that the #unload executes before my baseline is run.

I was surprised yesterday because I had loaded the Microdown baseline successfully many times, including from P12, and never ran into that issue.
